Repository po-ui/po-angular, pull requests merged in 2019-10, with the labels that each got.

#96 feat(ui): adicionado suporte para o idioma russo
  projects/templates/src/lib/components/po-modal-password-recovery/literals/i18n/po-modal-password-recovery-literals.ts
  projects/templates/src/lib/components/po-page-blocked-user/po-page-blocked-user.component.ts
  projects/templates/src/lib/components/po-page-change-password/literals/i18n/po-page-change-password-literals.ts
  projects/templates/src/lib/utils/util.spec.ts
  projects/templates/src/lib/utils/util.ts
  projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
  projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
  projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.spec.ts
  projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.ts
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.spec.ts
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.spec.ts
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
  projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.spec.ts
  projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
  projects/ui/src/lib/components/po-list-view/po-list-view-base.component.spec.ts
  projects/ui/src/lib/components/po-list-view/po-list-view-base.component.ts
  projects/ui/src/lib/components/po-loading/po-loading-overlay/po-loading-overlay-base.component.spec.ts
  projects/ui/src/lib/components/po-loading/po-loading-overlay/po-loading-overlay-base.component.ts
  projects/ui/src/lib/components/po-navbar/po-navbar-base.component.spec.ts
  projects/ui/src/lib/components/po-navbar/po-navbar-base.component.ts
  projects/ui/src/lib/components/po-page/po-page-detail/po-page-detail-base.component.spec.ts
  projects/ui/src/lib/components/po-page/po-page-detail/po-page-detail-base.component.ts
  projects/ui/src/lib/components/po-page/po-page-edit/po-page-edit-base.component.spec.ts
  projects/ui/src/lib/components/po-page/po-page-edit/po-page-edit-base.component.ts
  projects/ui/src/lib/components/po-page/po-page-list/po-page-list-base.component.spec.ts
  projects/ui/src/lib/components/po-page/po-page-list/po-page-list-base.component.ts
  projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
  projects/ui/src/lib/components/po-table/po-table-base.component.ts
  projects/ui/src/lib/services/po-dialog/po-dialog.component.spec.ts
  projects/ui/src/lib/services/po-dialog/po-dialog.component.ts
  projects/ui/src/lib/services/po-language/po-language.service.ts
  projects/ui/src/lib/utils/util.spec.ts
  projects/ui/src/lib/utils/util.ts
Labels: DTHFUI-2054, enhancement

#90 feat(notification): permitir alterar tempo de duração
  projects/ui/src/lib/services/po-notification/po-notification-base.service.spec.ts
  projects/ui/src/lib/services/po-notification/po-notification-base.service.ts
  projects/ui/src/lib/services/po-notification/po-notification.interface.ts
  projects/ui/src/lib/services/po-notification/po-notification.service.spec.ts
  projects/ui/src/lib/services/po-notification/po-notification.service.ts
  projects/ui/src/lib/services/po-notification/samples/sample-po-notification-labs/sample-po-notification-labs.component.html
  projects/ui/src/lib/services/po-notification/samples/sample-po-notification-labs/sample-po-notification-labs.component.ts
Labels: DTHFUI-1980

#102 fix(readme): corrigida instalação do angularcli
  README.md
Labels: DTHFUI-2080

#107 fix(dynamic-form): name ignorado quando utilizado po-lookup
  projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
Labels: DTHFUI-2096

#116 docs(issue): adiciona bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: DTHFUI-2133

#100 fix(page-dynamic-edit): corrige importação do DynamicForm
  projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.spec.ts
  projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
  projects/templates/src/lib/components/po-page-dynamic-edit/test/po-dynamic-form-stub-component.ts
Labels: DTHFUI-2076
