Repository po-ui/po-angular, pull requests merged in 2020-10, with the labels that each got.

#625 build: criada action para o build e deploy do portal
  .github/workflows/publish_po_angular_ci.yml
  angular.json
  projects/portal/src/web.config
Labels: DTHFUI-4304

#627 fix(ui/templates): ajusta declaracao incorreta dos event emitter
  projects/templates/src/lib/components/po-page-background/po-page-background.component.ts
  projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-base.component.ts
  projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
  projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group-base.component.ts
  projects/ui/src/lib/components/po-disclaimer/po-disclaimer-base.component.ts
  projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group-base.component.ts
  projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox-base.component.ts
  projects/ui/src/lib/components/po-field/po-clean/po-clean-base.component.ts
  projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
  projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.ts
  projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
  projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
  projects/ui/src/lib/components/po-field/po-radio-group/po-radio-group-base.component.ts
  projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-base.component.ts
  projects/ui/src/lib/components/po-field/po-select/po-select-base.component.ts
  projects/ui/src/lib/components/po-field/po-switch/po-switch-base.component.ts
  projects/ui/src/lib/components/po-field/po-textarea/po-textarea-base.component.ts
  projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
  projects/ui/src/lib/components/po-list-view/po-list-view-base.component.ts
  projects/ui/src/lib/components/po-table/po-table-base.component.ts
  projects/ui/src/lib/components/po-table/po-table-detail/po-table-detail.component.ts
  projects/ui/src/lib/components/po-tag/po-tag-base.component.ts
  projects/ui/src/lib/components/po-widget/po-widget-base.component.ts
Labels: DTHFUI-4310

#616 feat(lookup): inclusão da propriedade de busca avançada
  projects/ui/src/lib/components/po-field/po-field.module.ts
  projects/ui/src/lib/components/po-field/po-lookup/interfaces/po-lookup-advanced-filter.interface.ts
  projects/ui/src/lib/components/po-field/po-lookup/interfaces/po-lookup-filtered-items-params.interface.ts
  projects/ui/src/lib/components/po-field/po-lookup/interfaces/po-lookup-literals.interface.ts
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.spec.ts
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.html
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.spec.ts
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.ts
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.spec.ts
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.ts
  projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-hero/sample-po-lookup-hero.component.html
  projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-hero/sample-po-lookup-hero.component.ts
  projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.html
  projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.ts
  projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup.service.ts
  projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-filter.service.ts
  projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-modal.service.spec.ts
  projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-modal.service.ts
Labels: DTHFUI-4251

#630 build(portal): correção da geração do portal
  .github/workflows/publish_po_angular_ci.yml
Labels: DTHFUI-4327

#647 feat(number): adiciona a propriedade p-icon
  projects/ui/src/lib/components/po-field/po-number/po-number.component.html
  projects/ui/src/lib/components/po-field/po-number/samples/sample-po-number-labs/sample-po-number-labs.component.html
  projects/ui/src/lib/components/po-field/po-number/samples/sample-po-number-labs/sample-po-number-labs.component.ts
Labels: DTHFUI-4393, hacktoberfest-accepted

#652 feat(dialog): adiciona o evento close
  projects/ui/src/lib/services/po-dialog/interfaces/po-dialog.interface.ts
  projects/ui/src/lib/services/po-dialog/po-dialog.component.spec.ts
  projects/ui/src/lib/services/po-dialog/po-dialog.component.ts
  projects/ui/src/lib/services/po-dialog/samples/sample-po-dialog-labs/sample-po-dialog-labs.component.ts
Labels: DTHFUI-4409, hacktoberfest-accepted
