Repository po-ui/po-angular, pull requests merged in 2020-07, with the labels that each got.

#473 build: adequação do repo para desenvolvimento na branch dev
  .travis.yml
  CONTRIBUTING.md
Labels: DTHFUI-3739

#477 docs(page-dynamic-table): corrige descrição
  projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.module.ts
Labels: DTHFUI-3744

#474 docs(table): ajusta documentação sobre templates da coluna
  projects/ui/src/lib/components/po-table/interfaces/po-table-column.interface.ts
  projects/ui/src/lib/components/po-table/po-table-base.component.ts
  projects/ui/src/lib/components/po-table/po-table-cell-template/po-table-cell-template.directive.ts
  projects/ui/src/lib/components/po-table/po-table-column-template/po-table-column-template.directive.ts
Labels: DTHFUI-3741

#483 feat(rich-text): adiciona literais em russo
  projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-literals.ts
Labels: DTHFUI-3764

#487 feat(lookup): permite traduzir as literais usando o serviço do i18n
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.spec.ts
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
Labels: DTHFUI-3774

#488 feat(multiselect): permite traduzir as literais usando o serviço do i18n
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.spec.ts
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.ts
Labels: DTHFUI-3775

#491 feat(upload): permite traduzir as literais usando o serviço do i18n
  projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.spec.ts
  projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
  projects/ui/src/lib/components/po-field/po-upload/po-upload-file-restrictions/po-upload-file-restrictions.component.spec.ts
  projects/ui/src/lib/components/po-field/po-upload/po-upload-file-restrictions/po-upload-file-restrictions.component.ts
  projects/ui/src/lib/components/po-field/po-upload/po-upload.component.spec.ts
  projects/ui/src/lib/components/po-field/po-upload/po-upload.component.ts
Labels: DTHFUI-3782

#500 feat(page-job-scheduler): adiciona literais em russo
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-literals.ts
Labels: DTHFUI-3793

#499 feat(page-dynamic-table): permite traduzir literais usando serviço i18n
  projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
Labels: DTHFUI-3792

#498 feat(page-dynamic-detail): permite traduzir literais usando serviço i18n
  projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.ts
Labels: DTHFUI-3791

#497 feat(page-dynamic-edit): permite traduzir literais usando serviço i18n
  projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
Labels: DTHFUI-3790

#496 feat(page-change-password): permite traduzir literais usando i18n
  projects/templates/src/lib/components/po-page-change-password/po-page-change-password-base.component.spec.ts
  projects/templates/src/lib/components/po-page-change-password/po-page-change-password.component.ts
Labels: DTHFUI-3789

#504 doc(issues): melhora o template de abertura de issue
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: DTHFUI-3811

#518 feat(gulp): atualização da tarefa do Sonarqube
  gulpfile.js
Labels: DTHFUI-3888

#493 feat(po-menu): implement i18n to menu and menu filter
  projects/ui/src/lib/components/po-menu/po-menu-base.component.spec.ts
  projects/ui/src/lib/components/po-menu/po-menu-base.component.ts
  projects/ui/src/lib/components/po-menu/po-menu-filter/po-menu-filter-literals.interface.ts
  projects/ui/src/lib/components/po-menu/po-menu-filter/po-menu-filter.component.html
  projects/ui/src/lib/components/po-menu/po-menu-filter/po-menu-filter.component.ts
  projects/ui/src/lib/components/po-menu/po-menu.component.ts
Labels: DTHFUI-3786
