Repository po-ui/po-angular, pull requests merged in 2020-11, with the labels that each got.

#648 fix(password): sobrescreve a propriedade autocomplete
  projects/ui/src/lib/components/po-field/po-input-generic/po-input-generic.ts
  projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
  projects/ui/src/lib/components/po-field/po-password/po-password.component.spec.ts
  projects/ui/src/lib/components/po-field/po-password/po-password.component.ts
Labels: DTHFUI-4394, hacktoberfest-accepted

#662 feat(page-breadcrumb): define literais para idiomas suportados
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-favorite/po-breadcrumb-favorite.component.html
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-favorite/po-breadcrumb-favorite.component.spec.ts
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-favorite/po-breadcrumb-favorite.component.ts
Labels: DTHFUI-4440

#664 feat(lookup): adicionar evento p-change
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.spec.ts
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
  projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.html
Labels: DTHFUI-4446
