Repository po-ui/po-angular, pull requests merged in 2020-08, with the labels that each got.

#536 build: alteração da doc para volta ao fluxo via master
  .travis.yml
  CONTRIBUTING.md
Labels: DTHFUI-3958

#538 docs(changelog): atualiza informações dos commits
  CHANGELOG.md
Labels: DTHFUI-3969

#545 docs(sync): corrige link do repositorio de demonstração
  docs/guides/sync-fundamentals.md
Labels: DTHFUI-3984

#549 feat(page-job-scheduler): permite traduzir literais usando serviço i18n
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.ts
Labels: DTHFUI-3997

#550 feat(notification): permite traduzir literais usando serviço i18n
  projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.spec.ts
  projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.ts
Labels: DTHFUI-4001

#551 feat(dialog): permite traduzir literais usando serviço i18n
  projects/ui/src/lib/services/po-dialog/po-dialog.component.spec.ts
  projects/ui/src/lib/services/po-dialog/po-dialog.component.ts
Labels: DTHFUI-4002

#555 refactor(portal): remove a dependencia fs-path
  gulpfile.js
  package.json
  projects/portal/docs/index.js
  projects/portal/docs/processors/helpers/file-writer.js
Labels: DTHFUI-4010

#564 feat(table): permite traduzir literais usando serviço i18n
  projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
  projects/ui/src/lib/components/po-table/po-table-base.component.ts
  projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.ts
  projects/ui/src/lib/components/po-table/po-table.component.ts
Labels: DTHFUI-4060

#566 feat(navbar): permite traduzir literais usando serviço i18n
  projects/ui/src/lib/components/po-navbar/po-navbar-base.component.spec.ts
  projects/ui/src/lib/components/po-navbar/po-navbar-base.component.ts
  projects/ui/src/lib/components/po-navbar/po-navbar.component.ts
Labels: DTHFUI-4069

#570 feat(list-view): permite traduzir literais usando serviço i18n
  projects/ui/src/lib/components/po-list-view/po-list-view-base.component.spec.ts
  projects/ui/src/lib/components/po-list-view/po-list-view-base.component.ts
  projects/ui/src/lib/components/po-list-view/po-list-view.component.ts
Labels: DTHFUI-4076

#569 perf(switch): implementa ChangeDetectionStrategy.OnPush
  projects/ui/src/lib/components/po-field/po-switch/po-switch-base.component.spec.ts
  projects/ui/src/lib/components/po-field/po-switch/po-switch-base.component.ts
  projects/ui/src/lib/components/po-field/po-switch/po-switch.component.spec.ts
  projects/ui/src/lib/components/po-field/po-switch/po-switch.component.ts
Labels: DTHFUI-4075

#572 feat(modal-password-recovery): faz tradução de literais com serviço i18n
  projects/templates/src/lib/components/po-modal-password-recovery/po-modal-password-recovery-base.component.spec.ts
  projects/templates/src/lib/components/po-modal-password-recovery/po-modal-password-recovery-base.component.ts
  projects/templates/src/lib/components/po-modal-password-recovery/po-modal-password-recovery.component.ts
Labels: DTHFUI-4082

#482 Feat(page-login): Remember language selection stored in localstorage
  projects/templates/src/lib/components/po-page-background/po-page-background.component.spec.ts
  projects/templates/src/lib/components/po-page-background/po-page-background.component.ts
  projects/templates/src/lib/components/po-page-login/po-page-login-base.component.spec.ts
  projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
  projects/templates/src/lib/components/po-page-login/po-page-login.component.ts
Labels: DTHFUI-3763

#574 refactor(templates): remove função browserLanguage do utils
  projects/templates/src/lib/components/po-page-background/po-page-background.component.ts
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-summary/po-page-job-scheduler-summary.component.spec.ts
  projects/templates/src/lib/utils/util.spec.ts
  projects/templates/src/lib/utils/util.ts
Labels: DTHFUI-4086
