Repository po-ui/po-angular, pull requests merged in 2020-01, with the labels that each got.

#210 perf(divider): adiciona ChangeDetectionStrategy.OnPush
  projects/ui/src/lib/components/po-divider/po-divider.component.spec.ts
  projects/ui/src/lib/components/po-divider/po-divider.component.ts
Labels: DTHFUI-2580

#217 perf(tag): adiciona ChangeDetectionStrategy.OnPush
  projects/ui/src/lib/components/po-tag/po-tag.component.spec.ts
  projects/ui/src/lib/components/po-tag/po-tag.component.ts
Labels: DTHFUI-2593

#242 Correção CONTRIBUTING.md
  CONTRIBUTING.md
Labels: DTHFUI-2741

#247 docs(accordion): corrige palavra na documentação do accordion
  projects/ui/src/lib/components/po-accordion/po-accordion-base.component.ts
Labels: DTHFUI-2752
