Repository po-ui/po-angular, pull requests merged in 2022-11, with the labels that each got.

#1477 feat(image): novo componente po-image
  projects/ui/src/lib/components/components.module.ts
  projects/ui/src/lib/components/index.ts
  projects/ui/src/lib/components/po-image/index.ts
  projects/ui/src/lib/components/po-image/po-image-base.component.spec.ts
  projects/ui/src/lib/components/po-image/po-image-base.component.ts
  projects/ui/src/lib/components/po-image/po-image.component.html
  projects/ui/src/lib/components/po-image/po-image.component.spec.ts
  projects/ui/src/lib/components/po-image/po-image.component.ts
  projects/ui/src/lib/components/po-image/po-image.module.ts
  projects/ui/src/lib/components/po-image/samples/sample-po-image-basic/sample-po-image-basic.component.html
  projects/ui/src/lib/components/po-image/samples/sample-po-image-basic/sample-po-image-basic.component.ts
  projects/ui/src/lib/components/po-image/samples/sample-po-image-labs/sample-po-image-labs.component.html
  projects/ui/src/lib/components/po-image/samples/sample-po-image-labs/sample-po-image-labs.component.ts
  projects/ui/src/lib/components/po-image/samples/sample-po-image-travel/sample-po-image-travel.component.html
  projects/ui/src/lib/components/po-image/samples/sample-po-image-travel/sample-po-image-travel.component.ts
Labels: hacktoberfest-accepted

#1493 feat(page-job-scheduler): adiciona funcionalidade de template na parametrização
  projects/templates/src/lib/components/po-page-job-scheduler/index.ts
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-execution/po-page-job-scheduler-execution.component.html
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-execution/po-page-job-scheduler-execution.component.ts
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/index.ts
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/po-job-scheduler-parameters-template/index.ts
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/po-job-scheduler-parameters-template/po-job-scheduler-parameters-template.directive.spec.ts
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/po-job-scheduler-parameters-template/po-job-scheduler-parameters-template.directive.ts
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/po-page-job-scheduler-parameters.component.html
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/po-page-job-scheduler-parameters.component.ts
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.html
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.spec.ts
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.ts
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.module.ts
Labels: hacktoberfest-accepted, contribution

#1527 fix(datepicker): suporte locale russo
  projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.spec.ts
  projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
  projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
  projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.ts
  projects/ui/src/lib/services/po-language/po-language.constant.ts
  projects/ui/src/lib/services/po-language/po-language.interface.ts
  projects/ui/src/lib/services/po-language/po-language.service.spec.ts
  projects/ui/src/lib/services/po-language/po-language.service.ts
Labels: contribution
