Repository po-ui/po-angular, pull requests merged in 2022-10, with the labels that each got.

#1343 fix(language): adiciona limpeza das variáveis do `localStorage`
  projects/ui/src/lib/services/po-language/po-language.service.ts
Labels: contribution

#1419 feat(page-job-scheduler): adiciona a propriedade p-orientation
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-base.component.spec.ts
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-base.component.ts
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.html
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.spec.ts
  projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.ts
Labels: contribution

#1417 docs(table): corrige documentação das colunas para o formato MM
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-field.interface.ts
  projects/ui/src/lib/components/po-field/po-lookup/interfaces/po-lookup-column.interface.ts
  projects/ui/src/lib/components/po-table/interfaces/po-table-column.interface.ts
  projects/ui/src/lib/components/po-table/po-table-detail/po-table-detail-column.interface.ts
Labels: contribution

#1379 fix(select): ajusta o `OnTouched` do campo
  projects/ui/src/lib/components/po-field/po-select/po-select.component.spec.ts
  projects/ui/src/lib/components/po-field/po-select/po-select.component.ts
Labels: contribution

#1451 docs(breadcrumb): atualiza url base da API
  projects/ui/src/lib/components/po-breadcrumb/samples/sample-po-breadcrumb-labs/sample-po-breadcrumb-labs.component.html
Labels: contribution, hacktoberfest

#1449 docs(combo): atualiza url base da API
  projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-heroes-reactive-form/sample-po-combo-heroes-reactive-form.component.html
  projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-heroes-reactive-form/sample-po-combo-heroes-reactive-form.component.ts
  projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-heroes/sample-po-combo-heroes.component.html
  projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-heroes/sample-po-combo-heroes.component.ts
  projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-hotels/sample-po-combo-hotels.component.html
  projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-infinity-scroll/sample-po-combo-infinity-scroll.component.html
  projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-infinity-scroll/sample-po-combo-infinity-scroll.component.ts
  projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-labs/sample-po-combo-labs.component.html
  projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-transfer/sample-po-combo-transfer.component.html
Labels: contribution, hacktoberfest

#1450 docs(dynamic-form): atualiza url base da API
  projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
Labels: contribution, hacktoberfest

#1361 feat(page-dynamic-edit): adiciona parâmetro `p-literals`
  projects/templates/src/lib/components/po-page-dynamic-edit/index.ts
  projects/templates/src/lib/components/po-page-dynamic-edit/interfaces/po-page-dynamic-edit-literals.interface.ts
  projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.spec.ts
  projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
  projects/templates/src/lib/components/po-page-dynamic-edit/samples/sample-po-page-dynamic-edit-user/sample-po-page-dynamic-edit-user.component.html
  projects/templates/src/lib/components/po-page-dynamic-edit/samples/sample-po-page-dynamic-edit-user/sample-po-page-dynamic-edit-user.component.ts
Labels: contribution

#1445 docs(modal-password-recovery): altera url base da API
  projects/templates/src/lib/components/po-modal-password-recovery/samples/sample-po-modal-password-recovery-request/sample-po-modal-password-recovery-request.component.ts
Labels: contribution, hacktoberfest

#1471 docs(page-dynamic-edit): ajusta a documentação do componente
  projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
Labels: contribution, hacktoberfest

#1465 docs(select): atualiza url base da API
  projects/ui/src/lib/components/po-field/po-select/samples/sample-po-select-customer-registration/sample-po-select-customer-registration.component.html
  projects/ui/src/lib/components/po-field/po-select/samples/sample-po-select-customer-registration/sample-po-select-customer-registration.service.ts
Labels: contribution, hacktoberfest

#1447 docs(page-dynamic-detail): altera url base da API
  projects/templates/src/lib/components/po-page-dynamic-detail/samples/sample-po-page-dynamic-detail-user/sample-po-page-dynamic-detail-user.component.ts
Labels: contribution, hacktoberfest

#1488 docs(page-list): atualiza url base da API
  projects/ui/src/lib/components/po-page/po-page-list/samples/sample-po-page-list-labs/sample-po-page-list-labs.component.html
Labels: contribution, hacktoberfest

#1487 docs(stepper): atualiza url base da API
  projects/ui/src/lib/components/po-stepper/samples/sample-po-stepper-active/sample-po-stepper-active.service.ts
Labels: contribution, hacktoberfest

#1486 docs(http-interceptor): atualiza url base da API
  projects/ui/src/lib/interceptors/po-http-interceptor/samples/sample-po-http-interceptor-labs.component.ts
Labels: contribution, hacktoberfest

#1490 docs(page-login): atualiza url base da API
  projects/templates/src/lib/components/po-page-login/samples/sample-po-page-login-automatic-service/sample-po-page-login-automatic-service.component.html
  projects/templates/src/lib/components/po-page-login/samples/sample-po-page-login-human-resources/sample-po-page-login-human-resources.component.ts
  projects/templates/src/lib/components/po-page-login/samples/sample-po-page-login-labs/sample-po-page-login-labs.component.html
Labels: contribution, hacktoberfest

#1489 docs(page-job-scheduler): atualiza url base da API
  projects/templates/src/lib/components/po-page-job-scheduler/samples/sample-po-page-job-scheduler-background-process/sample-po-page-job-scheduler-background-process.component.html
Labels: contribution, hacktoberfest

#1440 docs(switch): alteração da documentação da propriedade p-label-position
  projects/ui/src/lib/components/po-field/po-switch/po-switch.component.ts
Labels: contribution, hacktoberfest

#1500 docs(tools-dynamic-form): atualiza URL base da API
  projects/portal/src/app/tools/tools-dynamic-form/tools-dynamic-form.component.ts
Labels: contribution, hacktoberfest

#1498 docs(sample-po-page-default-labs): atualiza URL base da API
  projects/ui/src/lib/components/po-page/po-page-default/samples/sample-po-page-default-labs/sample-po-page-default-labs.component.html
Labels: contribution, hacktoberfest

#1497 docs(sample-po-http-request-interceptor-labs): atualiza URL base da API
  projects/ui/src/lib/interceptors/po-http-request/samples/sample-po-http-request-interceptor-labs.component.html
Labels: contribution, hacktoberfest

#1495 refactor(portal): remove notification do Hacktoberfest
  projects/portal/src/app/app.component.ts
Labels: hacktoberfest-accepted
