Repository po-ui/po-angular, pull requests merged in 2023-10, with the labels that each got.

#1838 build: release v16.2.1
  CHANGELOG.md
  package.json
Labels: hacktoberfest-accepted, hacktoberfest

#1828 feat(breadcrumb): implementa definições do AnimaliaDS
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-base.component.spec.ts
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-base.component.ts
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-dropdown/po-breadcrumb-dropdown.component.html
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-dropdown/po-breadcrumb-dropdown.component.spec.ts
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-dropdown/po-breadcrumb-dropdown.component.ts
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-favorite/po-breadcrumb-favorite.component.html
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-favorite/po-breadcrumb-favorite.component.ts
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-item/po-breadcrumb-item.component.html
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-item/po-breadcrumb-item.component.spec.ts
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-item/po-breadcrumb-item.component.ts
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb.component.html
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb.component.spec.ts
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb.component.ts
  projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb.module.ts
  projects/ui/src/lib/components/po-popup/po-popup-base.component.ts
  projects/ui/src/lib/components/po-popup/po-popup.component.spec.ts
  projects/ui/src/lib/components/po-popup/po-popup.component.ts
Labels: hacktoberfest-accepted, contribution, hacktoberfest

#1827 feat(accordion): implementa definições do AnimaliaDS
  projects/ui/src/lib/components/po-accordion/index.ts
  projects/ui/src/lib/components/po-accordion/interfaces/po-accordion-literals.interface.ts
  projects/ui/src/lib/components/po-accordion/po-accordion-base.component.spec.ts
  projects/ui/src/lib/components/po-accordion/po-accordion-base.component.ts
  projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.html
  projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.spec.ts
  projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.ts
  projects/ui/src/lib/components/po-accordion/po-accordion-item/po-accordion-item.component.spec.ts
  projects/ui/src/lib/components/po-accordion/po-accordion-item/po-accordion-item.component.ts
  projects/ui/src/lib/components/po-accordion/po-accordion-manager/po-accordion-manager.component.html
  projects/ui/src/lib/components/po-accordion/po-accordion-manager/po-accordion-manager.component.spec.ts
  projects/ui/src/lib/components/po-accordion/po-accordion-manager/po-accordion-manager.component.ts
  projects/ui/src/lib/components/po-accordion/po-accordion.component.html
  projects/ui/src/lib/components/po-accordion/po-accordion.component.spec.ts
  projects/ui/src/lib/components/po-accordion/po-accordion.component.ts
  projects/ui/src/lib/components/po-accordion/po-accordion.module.ts
  projects/ui/src/lib/components/po-accordion/samples/sample-po-accordion-faq/sample-po-accordion-faq.component.html
  projects/ui/src/lib/components/po-accordion/samples/sample-po-accordion-labs/sample-po-accordion-labs.component.html
  projects/ui/src/lib/components/po-accordion/samples/sample-po-accordion-labs/sample-po-accordion-labs.component.ts
Labels: contribution, hacktoberfest

#1807 fix(input): adiciona indicação visual de campo inválido
  projects/ui/src/lib/components/po-field/po-input-generic/po-input-generic.spec.ts
  projects/ui/src/lib/components/po-field/po-input-generic/po-input-generic.ts
  projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
  projects/ui/src/lib/components/po-field/po-input/po-mask.ts
Labels: bug, hacktoberfest

#1843 build: release 16.3.0
  CHANGELOG.md
  package.json
Labels: hacktoberfest

#1846 fix(menu): corrige item seletor
  projects/ui/src/lib/components/po-menu/po-menu-item/po-menu-item.component.html
Labels: hacktoberfest

#1848 feat(dynamic-form): adiciona a propriedade `formField` para o `upload`
  projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
Labels: contribution, hacktoberfest

#1830 feat(tag): implementa variação de status neutral
  projects/ui/src/lib/components/po-tag/enums/po-tag-type.enum.ts
  projects/ui/src/lib/components/po-tag/po-tag-base.component.ts
  projects/ui/src/lib/components/po-tag/po-tag.component.spec.ts
  projects/ui/src/lib/components/po-tag/samples/sample-po-tag-labs/sample-po-tag-labs.component.ts
Labels: hacktoberfest

#1845 fix(table): mantém ordenação dos itens após uma pesquisa
  projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
  projects/ui/src/lib/components/po-table/po-table-base.component.ts
  projects/ui/src/lib/components/po-table/po-table.component.spec.ts
  projects/ui/src/lib/components/po-table/po-table.component.ts
Labels: hacktoberfest

#1840 feat(dynamic-view): implementa novas propriedades em fields
  projects/ui/src/lib/components/po-dynamic/index.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/interfaces/po-dynamic-view-request.interface.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.spec.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-field.interface.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.spec.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.service.spec.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.service.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/samples/sample-po-dynamic-view-employee-on-load/sample-po-dynamic-view-employee-on-load.component.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/samples/sample-po-dynamic-view-employee-on-load/sample-po-dynamic-view-employee-on-load.service.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/services/po-dynamic-view.service.spec.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/services/po-dynamic-view.service.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic.module.ts
Labels: hacktoberfest

#1852 fix(table): corrige valores padrão de propriedades
  projects/portal/src/app/home/home.component.html
  projects/portal/src/app/tools/tools-dynamic-form/tools-dynamic-form.component.html
  projects/portal/src/app/tools/tools-dynamic-view/tools-dynamic-view.component.html
  projects/templates/src/lib/components/po-page-dynamic-search/samples/sample-po-page-dynamic-search-hiring-processes/sample-po-page-dynamic-search-hiring-processes.component.html
  projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.html
  projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.html
  projects/ui/src/lib/components/po-chart/samples/sample-po-chart-coffee-ranking/sample-po-chart-coffee-ranking.component.html
  projects/ui/src/lib/components/po-container/samples/sample-po-container-dashboard/sample-po-container-dashboard.component.html
  projects/ui/src/lib/components/po-disclaimer-group/samples/sample-po-disclaimer-group-sw-planets/sample-po-disclaimer-group-sw-planets.component.html
  projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.html
  projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-multiple/sample-po-lookup-multiple.component.html
  projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-sw-films/sample-po-lookup-sw-films.component.html
  projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-heroes/sample-po-multiselect-heroes.component.html
  projects/ui/src/lib/components/po-field/po-switch/samples/sample-po-switch-order-reactive-form/sample-po-switch-order-reactive-form.component.html
  projects/ui/src/lib/components/po-field/po-switch/samples/sample-po-switch-order/sample-po-switch-order.component.html
  projects/ui/src/lib/components/po-field/po-url/samples/sample-po-url-shortener/sample-po-url-shortener.component.html
  projects/ui/src/lib/components/po-link/samples/sample-po-link-heroes/sample-po-link-heroes.component.html
  projects/ui/src/lib/components/po-page/po-page-default/samples/sample-po-page-default-dashboard/sample-po-page-default-dashboard.component.html
  projects/ui/src/lib/components/po-page/po-page-list/samples/sample-po-page-list-hiring-processes/sample-po-page-list-hiring-processes.component.html
  projects/ui/src/lib/components/po-table/po-table-base.component.ts
  projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.html
  projects/ui/src/lib/components/po-table/samples/sample-po-table-basic/sample-po-table-basic.component.html
  projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.component.html
  projects/ui/src/lib/components/po-table/samples/sample-po-table-draggable/sample-po-table-draggable.component.html
  projects/ui/src/lib/components/po-table/samples/sample-po-table-heroes/sample-po-table-heroes.component.html
  projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.ts
  projects/ui/src/lib/components/po-table/samples/sample-po-table-transport/sample-po-table-transport.component.html
  projects/ui/src/lib/components/po-table/samples/sample-po-table-with-api/sample-po-table-with-api.component.html
  projects/ui/src/lib/components/po-tree-view/samples/sample-po-tree-view-supermarket/sample-po-tree-view-supermarket.component.html
  projects/ui/src/lib/components/po-widget/samples/sample-po-widget-finance-dashboard/sample-po-widget-finance-dashboard.component.html
  projects/ui/src/lib/services/po-notification/samples/sample-po-notification-sales/sample-po-notification-sales.component.html
Labels: hacktoberfest

#1853 feat(rich-text): impede envio de dados ao escolher cor
  projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.html
Labels: contribution, hacktoberfest

#1850 feat(multiselect): implementa as definições do AnimaliaDS
  projects/ui/src/lib/components/po-field/po-field.module.ts
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.html
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.spec.ts
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.ts
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-literals.interface.ts
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-search/po-multiselect-search.component.html
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-search/po-multiselect-search.component.spec.ts
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-search/po-multiselect-search.component.ts
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.html
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.spec.ts
  projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.ts
  projects/ui/src/lib/components/po-listbox/po-item-list/po-item-list.component.html
  projects/ui/src/lib/components/po-listbox/po-item-list/po-item-list.component.ts
  projects/ui/src/lib/components/po-tag/index.ts
  projects/ui/src/lib/components/po-tag/interfaces/po-tag-literals.interface.ts
  projects/ui/src/lib/components/po-tag/po-tag-base.component.spec.ts
  projects/ui/src/lib/components/po-tag/po-tag-base.component.ts
  projects/ui/src/lib/components/po-tag/po-tag.component.html
  projects/ui/src/lib/components/po-tag/po-tag.component.spec.ts
  projects/ui/src/lib/components/po-tag/po-tag.component.ts
  projects/ui/src/lib/enums/po-key-code.enum.ts
Labels: enhancement, hacktoberfest-accepted, hacktoberfest
