Repository po-ui/po-angular, pull requests merged in 2024-01, with the labels that each got.

#1909 feat(menu): permite habilitar o automatic toggle
  projects/ui/src/lib/components/po-menu/po-menu-base.component.ts
  projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
  projects/ui/src/lib/components/po-menu/po-menu.component.ts
  projects/ui/src/lib/components/po-menu/samples/sample-po-menu-human-resources/sample-po-menu-human-resources.component.html
  projects/ui/src/lib/components/po-menu/samples/sample-po-menu-labs/sample-po-menu-labs.component.ts
Labels: enhancement

#1929 feat(po-dynamic-view): adiciona format aos valores
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.spec.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-field.interface.ts
Labels: status: awaiting author

#1926 fix(table): ajusta propriedade width
  projects/ui/src/lib/components/po-table/interfaces/po-table-column.interface.ts
  projects/ui/src/lib/components/po-table/po-table-base.component.ts
  projects/ui/src/lib/components/po-table/po-table.component.html
  projects/ui/src/lib/components/po-table/po-table.component.spec.ts
  projects/ui/src/lib/components/po-table/po-table.component.ts
Labels: enhancement

#1934 feat(po-dynamic-view): adicionado a propriedade params
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
  projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-field.interface.ts
Labels: contribution, DTHFUI-8248
